---
- name: My first playbook
  hosts: webservers
  become: true
  tasks:

  - name: Install docker.io
    apt:
       name: docker.io
       force_apt_get: yes
       update_cache: yes
       state: present

  - name: Install python3-pip
    apt:
       force_apt_get: yes
       name: python3-pip
       state: present

  - name: Install Docker python using pip
    pip:
       name: docker
       state: present

  - name: Download and Launch cyberxsecurity/dvwa
    docker_container:
       name: dvwa
       image: cyberxsecurity/dvwa
       state: started
       restart_policy: always
       published_ports: 80:80

  - name: Docker Service is started
    systemd:
       enabled: yes
       name: docker
